name: pipeline

on:
  push:
    branches:
      - main
  pull_request:
  release:
    types:
      - published

jobs:
  backend-go:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: 🖥️ setup golang
        uses: actions/setup-go@v5
        with:
          go-version-file: backend-go/go.mod
      - name: 🧪 run tests
        working-directory: backend-go
        run: go test ./tests/... -coverprofile=./coverage.txt -coverpkg=./internal/...
      - name: 📊 upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: 🔨 build main
        working-directory: backend-go
        run: go build .
      - name: 💅 check gofmt
        working-directory: backend-go
        run: test -z "$(gofmt -l .)"
        env:
          GOFLAGS: -mod=readonly

  frontend:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
      - name: 🖥️ setup node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: frontend/package.json
      - name: ⚙️ install dependencies
        run: yarn install
        working-directory: frontend
      - name: 🧪 lint
        run: yarn run lint
        working-directory: frontend
      - name: 💅 check format
        run: yarn run format:check
        working-directory: frontend
      - name: 🔨 check build
        run: yarn run build
        working-directory: frontend

  docker:
    env:
      REGION: europe-west1
      COMMIT_IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/refugenavigator:${{ github.event.pull_request.head.sha || github.sha }}
      TAG_IMAGE_NAME: eu.gcr.io/${{ secrets.GCP_PROJECT_ID }}/refugenavigator:${{ github.ref_name }}
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: 🔑 authenticate to GCP
        uses: google-github-actions/auth@v2.1.10
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}
      - name: ☁️ set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2.1.4
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - name: 🔐 login to docker registry
        run: gcloud auth configure-docker
      - name: 📥 pull from registry with commit SHA for docker cache
        if: github.event_name != 'pull_request'
        run: |
          docker pull ${{ env.COMMIT_IMAGE_NAME }}
      - name: 🔨 build docker image
        run: docker build -t ${{ env.COMMIT_IMAGE_NAME }} --cache-from ${{ env.COMMIT_IMAGE_NAME }} .
      - name: 🚀 run docker
        id: run
        run: |
          container_id=$(docker run -d -p 8080:8080 ${{ env.COMMIT_IMAGE_NAME }})
          echo "container_id=$container_id" >> $GITHUB_OUTPUT
      - name: 🔍 check docker
        run: |
          curl http://localhost:8080/api/git-tag
          echo ""
          git describe --tags --always
      - name: 🛑 stop docker
        run: docker stop ${{ steps.run.outputs.container_id }}
      - name: 📤 push to registry with commit SHA
        run: |
          docker push ${{ env.COMMIT_IMAGE_NAME }}
      - name: 📤 push to registry with tag
        if: github.event_name == 'release'
        run: |
          docker tag ${{ env.COMMIT_IMAGE_NAME }} ${{ env.TAG_IMAGE_NAME }}
          docker push ${{ env.TAG_IMAGE_NAME }}
      - name: ✨ deploy to Cloud Run
        run: |
          SERVICE_NAME="${{ github.event_name == 'release' && 'refugenavigator' || 'devrefugenavigator' }}"
          IMAGE_NAME="${{ github.event_name == 'release' && env.TAG_IMAGE_NAME || env.COMMIT_IMAGE_NAME }}"
          echo "Deploying ${IMAGE_NAME} to Cloud Run..."
          gcloud run deploy $SERVICE_NAME \
            --image $IMAGE_NAME \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --clear-vpc-connector \
            --clear-network
